In [1]:
import numpy as np

In [15]:
#1.-Crear un array
array = np.random.randint(1, 101, size=10)
print("Array generado:", array)

Array generado: [87 13 69 68 10 94 45  7 56  8]


In [16]:
#2.-Reshape
matriz = array.reshape(2, 5)
print("\nMatriz 2x5:")
print(matriz)


Matriz 2x5:
[[87 13 69 68 10]
 [94 45  7 56  8]]


In [17]:
#3.-Indexación y slicing
primera_fila = matriz[0]  
print("\nPrimera fila:", primera_fila)

# 3. Extraer la última columna
ultima_columna = matriz[:, -1]  
print("Última columna:", ultima_columna)


Primera fila: [87 13 69 68 10]
Última columna: [10  8]


In [18]:
#4.-Modificación
matriz[1] = 0  
print("\nMatriz con la segunda fila modificada:")
print(matriz)


Matriz con la segunda fila modificada:
[[87 13 69 68 10]
 [ 0  0  0  0  0]]


In [ ]:
#Parte 2: Operaciones básicas con NumPy

In [23]:
# 1.- Crear dos arrays aleatorios
array1 = np.random.randint(1, 51, size=5)  
array2 = np.random.randint(1, 51, size=5)

# Mostrar los arrays originales
print("Array 1:", array1)
print("Array 2:", array2)

# 2. Operaciones
# Suma de arrays
suma = array1 + array2
print("\nSuma de arrays:", suma)

# Multiplicación de arrays
multiplicacion = array1 * array2
print("Multiplicación de arrays:", multiplicacion)

# 3. Estadísticas
# Promedio
promedio_suma = np.mean(suma)
promedio_mult = np.mean(multiplicacion)

# Desviación estándar
std_suma = np.std(suma)
std_mult = np.std(multiplicacion)

# Mostrar resultados estadísticos
print("\nEstadísticas de la suma:")
print(f"Promedio: {promedio_suma:.2f}")
print(f"Desviación estándar: {std_suma:.2f}")

print("\nEstadísticas de la multiplicación:")
print(f"Promedio: {promedio_mult:.2f}")
print(f"Desviación estándar: {std_mult:.2f}")

Array 1: [38 25 28 29 26]
Array 2: [50 15  6 27 17]

Suma de arrays: [88 40 34 56 43]
Multiplicación de arrays: [1900  375  168  783  442]

Estadísticas de la suma:
Promedio: 52.20
Desviación estándar: 19.29

Estadísticas de la multiplicación:
Promedio: 733.60
Desviación estándar: 615.87


In [27]:
#2.- Generar array de 20 números aleatorios entre 0 y 1
array_original = np.random.random(20)

# Mostrar el array original
print("Array original:")
print(array_original)
print("\nValores redondeados a 4 decimales:")
print(np.round(array_original, 4))

array_modificado = array_original.copy()

# máscaras booleanas
array_modificado[array_modificado < 0.5] = 0  
array_modificado[array_modificado >= 0.5] = 1  

print("\nArray después de aplicar las condiciones:")
print(array_modificado)

# Mostrar estadísticas
print("\nEstadísticas:")
print(f"Cantidad de ceros: {np.sum(array_modificado == 0)}")
print(f"Cantidad de unos: {np.sum(array_modificado == 1)}")
print(f"Proporción de unos: {np.mean(array_modificado):.2%}")

Array original:
[0.9525829  0.69774195 0.53585264 0.14103493 0.27996853 0.24035079
 0.10944469 0.93531994 0.76502606 0.27595462 0.1677133  0.22745328
 0.37990791 0.45684251 0.43008242 0.3272863  0.23268164 0.60533208
 0.3003456  0.08204284]

Valores redondeados a 4 decimales:
[0.9526 0.6977 0.5359 0.141  0.28   0.2404 0.1094 0.9353 0.765  0.276
 0.1677 0.2275 0.3799 0.4568 0.4301 0.3273 0.2327 0.6053 0.3003 0.082 ]

Array después de aplicar las condiciones:
[1. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]

Estadísticas:
Cantidad de ceros: 14
Cantidad de unos: 6
Proporción de unos: 30.00%


In [32]:
matriz1 = np.random.randint(1, 10, size=(3, 3))
matriz2 = np.random.randint(1, 10, size=(3, 3))

# Mostrar las matrices originales
print("Matriz 1:")
print(matriz1)
print("\nMatriz 2:")
print(matriz2)

# Calcular el producto escalar usando diferentes métodos
producto_dot = np.dot(matriz1, matriz2)
print("\nProducto escalar:")
print(producto_dot)

# Mostrar dimensiones del resultado
print("\nDimensiones del resultado:", producto_dot.shape)

Matriz 1:
[[9 4 5]
 [5 3 9]
 [8 5 2]]

Matriz 2:
[[7 1 5]
 [4 6 7]
 [5 2 8]]

Producto escalar:
[[104  43 113]
 [ 92  41 118]
 [ 86  42  91]]

Dimensiones del resultado: (3, 3)


In [33]:
##Parte 3: Análisis de datos con NumPy

In [53]:
import pandas as pd

# Generar matriz de datos aleatorios
datos = np.random.randint(1, 21, size=(5, 4))

# Crear DataFrame con nombres descriptivos
df = pd.DataFrame(
    datos,
    columns=['Altura (cm)', 'Peso (kg)', 'Edad', 'Presión sistólica'],
    index=['Persona 1', 'Persona 2', 'Persona 3', 'Persona 4', 'Persona 5']
)
print("Matriz de datos de personas:")
print(df)

Matriz de datos de personas:
           Altura (cm)  Peso (kg)  Edad  Presión sistólica
Persona 1           11          7     1                  1
Persona 2           20         13     9                  3
Persona 3            7          6     8                  9
Persona 4            5          1    19                 10
Persona 5           12         15     9                 20


In [54]:
##Estadisticas

In [55]:
# Calcular la media de cada columna
media_columnas = df.mean()

print("Media de cada columna:")
print(media_columnas)


# Encontrar el valor máximo de cada fila
max_filas = df.max(axis=1)

# Encontrar el valor mínimo de cada fila
min_filas = df.min(axis=1)

print("Valor máximo de cada fila:")
print(max_filas)

print("\nValor mínimo de cada fila:")
print(min_filas)


# Ordenar las filas según los valores de la columna "Peso"
df_ordenado = df.sort_values(by='Peso (kg)')

print("DataFrame ordenado por 'Peso':")
print(df_ordenado)

Media de cada columna:
Altura (cm)          11.0
Peso (kg)             8.4
Edad                  9.2
Presión sistólica     8.6
dtype: float64
Valor máximo de cada fila:
Persona 1    11
Persona 2    20
Persona 3     9
Persona 4    19
Persona 5    20
dtype: int32

Valor mínimo de cada fila:
Persona 1    1
Persona 2    3
Persona 3    6
Persona 4    1
Persona 5    9
dtype: int32
DataFrame ordenado por 'Peso':
           Altura (cm)  Peso (kg)  Edad  Presión sistólica
Persona 4            5          1    19                 10
Persona 3            7          6     8                  9
Persona 1           11          7     1                  1
Persona 2           20         13     9                  3
Persona 5           12         15     9                 20
